### PR TITLE
[WIP] Example of a timeline tutorial

### PR DESCRIPTION
**Pull request by willingc**
This is a very rough pass. I would modify the time markers in the  `JupyterHub-Tutorial.ipynb` to link the user to the spot in the YouTube video. I would also add keypoints or links to JupyterHub docs or repos as a convenience for the user. 

If you want to iterate on this, great. If not, no worries. I will use with our interns this summer :smile:

### CODE REVIEW

**Comment by minrk** [comment]
This is great! Thanks especially for taking the time to do the timeline. I like to keep talk repos as artifacts of the presentation, so I really like adding the timeline here, but I'd like to move the sphinx stuff and removal of the presentation to a new repo on the org, [which I've just created](https://github.com/jupyterhub/jupyterhub-tutorial).

For tutorial materials, I find that the format (and content, to some degree) for self-guided content and with an instructor in the room are quite different. Often notebooks work well for both, but the sysadmin-y nature of JupyterHub make them a poor fit for much of this one. I think we can rework the 'live' tutorial content here into a full-text sphinx tutorial for people to follow on their own [over here](https://github.com/jupyterhub/jupyterhub-tutorial).

So what I'll do here is:
1. merge this
2. push the result to jupyterhub/jupyterhub-tutorial
3. revert this repo to just the timeline, before the sphinx stuff

and then we can start the work of making the official tutorial repo more of a general, long-lived repo. How does that sound?

**Comment by willingc** [comment]
Sounds great! If you have the images used in the slide deck handy those would be good to move over as well. I think we can use them in a one page cheatsheet re: JupyterHub.

On another note, I have been playing around with the Docker for Mac beta. It's tons faster, no more boot2docker (yay!), and works essentially like docker on Linux. When I get a chance, I'm going to see if I can get the Windows beta too. The general release of this will likely simplify JH deployment quite a bit.

**Comment by minrk** [comment]
Awesome, that should be all done now, and we can start to fill out [the repo](https://github.com/jupyterhub/jupyterhub-tutorial). Do you think it's worthwhile to have a very short single-page version in the main JupyterHub docs that goes from zero-to-GitHub+Docker, and then links to this more detailed tutorial and the reference deployments?

**Comment by willingc** [comment]
Yes, I think a one page that links to this is a great idea. Will do.

**Pull request merged**
